# Generated by Django 6.0.7 on 2026-07-15 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('mood', models.CharField(choices=[('motivated', 'Motivated'), ('calm', 'Calm'), ('focused', 'Focused'), ('coding', 'Coding'), ('study', 'Study'), ('gaming', 'Gaming')], max_length=30)),
                ('style', models.CharField(choices=[('minimal', 'Minimal'), ('cyberpunk', 'Cyberpunk'), ('abstract', 'Abstract'), ('nature', 'Nature'), ('retro', 'Retro'), ('anime', 'Anime Inspired')], max_length=30)),
                ('color_palette', models.CharField(max_length=50)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], max_length=20)),
                ('quote', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('image', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallpaper',
                'verbose_name_plural': 'Wallpapers',
                'ordering': ['-created_at'],
            },
        ),
    ]
