# Generated by Django 6.0.7 on 2026-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='character',
            field=models.CharField(blank=True, choices=[('anime_warrior', 'Anime Warrior'), ('pirate_captain', 'Pirate Captain'), ('saiyan_inspired', 'Saiyan Inspired'), ('shinobi', 'Shinobi'), ('superhero', 'Superhero'), ('samurai', 'Samurai'), ('cyber_ninja', 'Cyber Ninja'), ('wizard', 'Wizard')], max_length=30, null=True),
        ),
    ]
