# Generated by Django 6.0.7 on 2026-07-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_wallpaper_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='prompt',
            field=models.TextField(max_length=500),
        ),
    ]
